import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { baseCompile } from '@intlify/message-compiler'

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = resolve(__dirname, '..')
const sourceDir = resolve(rootDir, 'src/i18n')
const outputDir = resolve(sourceDir, 'compiled')
const locales = ['en', 'tr']

const header = `// This file is generated by scripts/compile-i18n.mjs.
// Do not edit it directly.

`

function compileMessage(message) {
  const normalizedMessage = message.includes("{'@'}")
    ? message
    : message.replaceAll('@', "{'@'}")

  const { code } = baseCompile(normalizedMessage, {
    mode: 'arrow',
    needIndent: false,
  })

  return code
}

function serialize(value, path = [], insideArray = false) {
  if (typeof value === 'string') {
    return insideArray ? JSON.stringify(value) : compileMessage(value)
  }

  if (Array.isArray(value)) {
    return `[${value.map((item, index) => serialize(item, path.concat(index), true)).join(',')}]`
  }

  if (value && typeof value === 'object') {
    const entries = Object.entries(value).map(([key, child]) => {
      return `${JSON.stringify(key)}:${serialize(child, path.concat(key), insideArray)}`
    })

    return `{${entries.join(',')}}`
  }

  return JSON.stringify(value)
}

await mkdir(outputDir, { recursive: true })

for (const locale of locales) {
  const sourcePath = resolve(sourceDir, `${locale}.json`)
  const outputPath = resolve(outputDir, `${locale}.js`)
  const messages = JSON.parse(await readFile(sourcePath, 'utf8'))
  const moduleSource = `${header}export default ${serialize(messages)}\n`

  await writeFile(outputPath, moduleSource)
}
